### ISSUE TITLE
Blur Filter takes too long to be completed

### ISSUE THREAD

**Issue by brunobraga95** [jrichelsen/FotoFinish#2]
description
=========
When trying to apply blur filter to an image, the time that it takes to be finished and fully applied is too long and proportional to the size of the image.

actions performed
==============
1-  Open a file Test.png in FotoFinish using File->Open
2- Use the Slider called Gaussian Blur to apply blur effect

expected results
=============
As result it was expected that the given image Test.png, acquired a blur effect proportional to the position of the slider .

actual results
==========
The effect takes to long to be applied. In fact when the image is large enough it is often not even applied and the program crashes. 

environment
==========
Windows 10, 64-bit Operating System, x64-based processor
NetBeans IDE 8.0.2 
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

**Comment by jrichelsen** [comment]
thanks for the bug report, developing a more optimized routine now
